   version: '3.8'
   services:
     app:
       build:
         context: .
         dockerfile: Dockerfile
       container_name: laravel_app
       restart: unless-stopped
       volumes:
         - .:/var/www
         - ./vendor:/var/www/vendor
         - ./node_modules:/var/www/node_modules
       ports:
         - "8000:80"
       networks:
         - laravel

     mysql:
       image: mysql:5.7
       container_name: laravel_mysql
       restart: unless-stopped
       environment:
         MYSQL_DATABASE: laravel
         MYSQL_ROOT_PASSWORD: root
         MYSQL_USER: laraveluser
         MYSQL_PASSWORD: laravelpw
       volumes:
         - mysql_data:/var/lib/mysql
       ports:
         - "3306:3306"
       networks:
         - laravel

   networks:
     laravel:

   volumes:
     mysql_data:
   
